// Generated by CoffeeScript 1.10.0
(function() {
  var addLocals, app, bodyParser, env, express;

  express = require('express');

  bodyParser = require('body-parser').json;

  app = express();

  app.port = process.env.PORT || 3000;

  env = process.env.NODE_ENV || "development";

  app.use(express["static"](process.cwd() + '/public'));

  app.set('view engine', 'jade');

  app.use(bodyParser());

  app.get('/', function(req, res) {
    res.send('Hello World!');
    console.warn("error 404: ", req.url);
    res.statusCode = 404;
    return res.render('404', 404);
  });

  addLocals = function(req, res, next) {
    res.locals.requestPath = req.path;
    res.locals.bodyClass = req.path.split("/")[1] || "home";
    return next();
  };

  app.use(addLocals);

  module.exports = app;

}).call(this);
